#!/usr/bin/env python3
"""Core diagnostics for PartQMMM MD-ensemble analysis.

Geometry quantities (H bonds, Zn-water distances, ion proximity) use the same
triclinic minimum-image machinery as qmmm_partition.py. Electrostatic quantities
are evaluated from the exact embedding sites returned by partition_frame(), so
shift/RCD boundary treatments are analyzed exactly as a downstream QM engine
would see them in the generated point-charge field.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional
import math
import sys
import numpy as np
import mdtraj as md

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import qmmm_partition as qp

# Potential generated by +1 e at 1 Angstrom is 14.399645... V.
# Thus raw sum(q/r) [e/A] * this factor -> V; raw field [e/A^2] -> V/A.
COULOMB_V_ANGSTROM_PER_E = 14.3996454784255


@dataclass
class RawFrame:
    frame_index: int
    xyz_A: np.ndarray
    box_vectors_A: Optional[np.ndarray]
    time_ps: Optional[float]


def iter_trajectory_frames(traj_path: str | Path, mdtop,
                           frames: str = "0:None:1") -> Iterable[RawFrame]:
    """Yield requested physical trajectory frames with Angstrom coordinates."""
    traj_path = str(traj_path)
    start, stop, stride = qp._parse_frames(frames)
    lower = traj_path.lower()
    single = lower.endswith((".rst7", ".rst", ".inpcrd", ".ncrst", ".pdb"))

    if single:
        if start > 0 or (stop is not None and stop <= 0):
            return
        if lower.endswith(".pdb"):
            t = md.load_pdb(traj_path)
        else:
            t = md.load(traj_path, top=mdtop)
        if t.n_atoms != mdtop.n_atoms:
            raise ValueError(
                f"trajectory {traj_path} has {t.n_atoms} atoms but topology has {mdtop.n_atoms}"
            )
        box = None
        if t.unitcell_vectors is not None:
            box = np.asarray(t.unitcell_vectors[0], dtype=float) * 10.0
        time_ps = None
        if getattr(t, "time", None) is not None and len(t.time):
            time_ps = float(t.time[0])
        yield RawFrame(0, np.asarray(t.xyz[0], dtype=float) * 10.0, box, time_ps)
        return

    chunks = md.iterload(traj_path, top=mdtop, chunk=100, skip=start, stride=stride)
    seen = 0
    for chunk in chunks:
        if chunk.n_atoms != mdtop.n_atoms:
            raise ValueError(
                f"trajectory {traj_path} has {chunk.n_atoms} atoms but topology has {mdtop.n_atoms}"
            )
        for j in range(chunk.n_frames):
            global_idx = start + seen * stride
            seen += 1
            if stop is not None and global_idx >= stop:
                return
            box = None
            if chunk.unitcell_vectors is not None:
                box = np.asarray(chunk.unitcell_vectors[j], dtype=float) * 10.0
            time_ps = None
            if getattr(chunk, "time", None) is not None and len(chunk.time) > j:
                time_ps = float(chunk.time[j])
            yield RawFrame(
                global_idx,
                np.asarray(chunk.xyz[j], dtype=float) * 10.0,
                box,
                time_ps,
            )


def protein_pdb_resnum(residue, resnum_offset: int) -> Optional[int]:
    """Map topology resSeq back to original PDB numbering for protein residues."""
    try:
        is_protein = bool(residue.is_protein)
    except Exception:
        is_protein = False
    if not is_protein:
        return None
    return int(residue.resSeq - resnum_offset)


def atom_label(mdtop, atom_index: int, resnum_offset: int) -> str:
    atom = mdtop.atom(int(atom_index))
    pdbn = protein_pdb_resnum(atom.residue, resnum_offset)
    if pdbn is None:
        return f"{atom.residue.name}{atom.residue.resSeq}:{atom.name}"
    return f"{atom.residue.name}{pdbn}:{atom.name}"


def partner_group(residue, resnum_offset: int) -> str:
    name = residue.name.upper()
    if name == "AZM":
        return "AZM"
    pdbn = protein_pdb_resnum(residue, resnum_offset)
    if pdbn is not None:
        if name in qp.HID_HIE_VARIANTS or name == "HIS":
            return f"HIS{pdbn}"
        return f"{name}{pdbn}"
    return f"{residue.name}{residue.resSeq}"


def structured_hbond_contacts(mdtop, spec: qp.QMRegionSpec, xyz_A: np.ndarray,
                              box_vectors_A: Optional[np.ndarray],
                              resnum_offset: int,
                              distance_cutoff_A: float = 3.5,
                              angle_cutoff_deg: float = 140.0) -> list[dict]:
    """Return structured records for the exact adaptive-water H-bond criterion."""
    waters = spec.water_records
    if not waters:
        return []
    rows: list[dict] = []
    o_indices = np.asarray([w.oxygen_index for w in waters], dtype=int)
    o_positions = xyz_A[o_indices]

    # Water donor -> fixed-core acceptor.
    for acc in spec.core_hbond_acceptors:
        disp = qp.minimum_image_displacement(o_positions - xyz_A[acc], box_vectors_A)
        distances = np.linalg.norm(disp, axis=1)
        for wi in np.flatnonzero(distances <= distance_cutoff_A):
            water = waters[int(wi)]
            best_angle = -1.0
            best_h = None
            for h in water.hydrogen_indices:
                angle = qp.pbc_angle_dha(
                    xyz_A[water.oxygen_index], xyz_A[h], xyz_A[acc], box_vectors_A
                )
                if angle > best_angle:
                    best_angle, best_h = angle, h
            if best_angle >= angle_cutoff_deg:
                a = mdtop.atom(acc)
                rows.append({
                    "water_residue_index": water.residue_index,
                    "water_resseq": water.residue_seq,
                    "water_oxygen_index": water.oxygen_index,
                    "direction": "water_donor",
                    "partner_group": partner_group(a.residue, resnum_offset),
                    "partner_resname": a.residue.name,
                    "partner_resseq": a.residue.resSeq,
                    "partner_pdb_resnum": protein_pdb_resnum(a.residue, resnum_offset),
                    "partner_atom": a.name,
                    "partner_atom_index": a.index,
                    "donor_hydrogen_index": int(best_h),
                    "distance_A": float(distances[wi]),
                    "angle_deg": float(best_angle),
                })

    # Fixed-core donor -> water acceptor.
    for donor, hydrogens in spec.core_hbond_donors.items():
        disp = qp.minimum_image_displacement(o_positions - xyz_A[donor], box_vectors_A)
        distances = np.linalg.norm(disp, axis=1)
        for wi in np.flatnonzero(distances <= distance_cutoff_A):
            water = waters[int(wi)]
            best_angle = -1.0
            best_h = None
            for h in hydrogens:
                angle = qp.pbc_angle_dha(
                    xyz_A[donor], xyz_A[h], xyz_A[water.oxygen_index], box_vectors_A
                )
                if angle > best_angle:
                    best_angle, best_h = angle, h
            if best_angle >= angle_cutoff_deg:
                d = mdtop.atom(donor)
                rows.append({
                    "water_residue_index": water.residue_index,
                    "water_resseq": water.residue_seq,
                    "water_oxygen_index": water.oxygen_index,
                    "direction": "core_donor",
                    "partner_group": partner_group(d.residue, resnum_offset),
                    "partner_resname": d.residue.name,
                    "partner_resseq": d.residue.resSeq,
                    "partner_pdb_resnum": protein_pdb_resnum(d.residue, resnum_offset),
                    "partner_atom": d.name,
                    "partner_atom_index": d.index,
                    "donor_hydrogen_index": int(best_h),
                    "distance_A": float(distances[wi]),
                    "angle_deg": float(best_angle),
                })
    return rows


def zn_coordinated_water_contacts(mdtop, spec: qp.QMRegionSpec, xyz_A: np.ndarray,
                                   box_vectors_A: Optional[np.ndarray],
                                   cutoff_A: float = qp.DEFAULT_ZN_WATER_CUTOFF_A) -> list[dict]:
    """Return structured records for waters selected by direct Zn--O coordination."""
    if cutoff_A <= 0 or not spec.metal_indices or not spec.water_records:
        return []
    rows: list[dict] = []
    oxy = np.asarray([w.oxygen_index for w in spec.water_records], dtype=int)
    opos = xyz_A[oxy]
    for metal_idx in spec.metal_indices:
        metal = mdtop.atom(metal_idx)
        disp = qp.minimum_image_displacement(opos - xyz_A[metal_idx], box_vectors_A)
        dist = np.linalg.norm(disp, axis=1)
        for wi in np.flatnonzero(dist <= cutoff_A):
            w = spec.water_records[int(wi)]
            rows.append({
                "water_residue_index": int(w.residue_index),
                "water_resseq": int(w.residue_seq),
                "water_oxygen_index": int(w.oxygen_index),
                "metal_atom_index": int(metal_idx),
                "metal_resname": metal.residue.name,
                "metal_resseq": int(metal.residue.resSeq),
                "metal_atom_name": metal.name,
                "zn_o_distance_A": float(dist[wi]),
                "zn_water_cutoff_A": float(cutoff_A),
            })
    return rows


def nearest_zn_water(spec: qp.QMRegionSpec, xyz_A: np.ndarray,
                     box_vectors_A: Optional[np.ndarray]) -> dict:
    if not spec.metal_indices or not spec.water_records:
        return {
            "nearest_zn_water_A": math.nan,
            "nearest_zn_water_residue_index": None,
            "nearest_zn_water_resseq": None,
        }
    zn = spec.metal_indices[0]
    oxy = np.asarray([w.oxygen_index for w in spec.water_records], dtype=int)
    disp = qp.minimum_image_displacement(xyz_A[oxy] - xyz_A[zn], box_vectors_A)
    dist = np.linalg.norm(disp, axis=1)
    wi = int(np.argmin(dist))
    w = spec.water_records[wi]
    return {
        "nearest_zn_water_A": float(dist[wi]),
        "nearest_zn_water_residue_index": int(w.residue_index),
        "nearest_zn_water_resseq": int(w.residue_seq),
    }


def ion_proximity_metrics(mdtop, spec: qp.QMRegionSpec, xyz_A: np.ndarray,
                         box_vectors_A: Optional[np.ndarray],
                         qm_real_indices: Iterable[int]) -> dict:
    qm_ids = np.asarray(list(qm_real_indices), dtype=int)
    metrics = {
        "nearest_free_ion_A": math.nan,
        "nearest_positive_ion_A": math.nan,
        "nearest_negative_ion_A": math.nan,
        "nearest_na_A": math.nan,
        "nearest_cl_A": math.nan,
        "nearest_free_ion_label": "",
    }
    if not spec.ion_records or len(qm_ids) == 0:
        return metrics

    best_all = (float("inf"), "")
    best_pos = float("inf")
    best_neg = float("inf")
    best_na = float("inf")
    best_cl = float("inf")
    for ion in spec.ion_records:
        ion_ids = [i for i in ion.atom_indices if qp._is_real_atom(mdtop.atom(i))]
        if not ion_ids:
            continue
        # Ion records are normally one atom, but support small multi-atom ions.
        best = float("inf")
        for ii in ion_ids:
            disp = qp.minimum_image_displacement(
                xyz_A[qm_ids] - xyz_A[ii], box_vectors_A
            )
            best = min(best, float(np.min(np.linalg.norm(disp, axis=1))))
        label = f"{ion.residue_name}{ion.residue_seq}({ion.net_charge:+.3f}e)"
        if best < best_all[0]:
            best_all = (best, label)
        if ion.net_charge > 0:
            best_pos = min(best_pos, best)
        elif ion.net_charge < 0:
            best_neg = min(best_neg, best)
        name = ion.residue_name.upper()
        if name in {x.upper() for x in qp.POSITIVE_ION_RESNAMES} and name.startswith(("NA", "SOD")):
            best_na = min(best_na, best)
        if name in {x.upper() for x in qp.NEGATIVE_ION_RESNAMES} and name.startswith(("CL", "CLA")):
            best_cl = min(best_cl, best)

    def finite_or_nan(x):
        return float(x) if np.isfinite(x) else math.nan

    metrics.update({
        "nearest_free_ion_A": finite_or_nan(best_all[0]),
        "nearest_positive_ion_A": finite_or_nan(best_pos),
        "nearest_negative_ion_A": finite_or_nan(best_neg),
        "nearest_na_A": finite_or_nan(best_na),
        "nearest_cl_A": finite_or_nan(best_cl),
        "nearest_free_ion_label": best_all[1],
    })
    return metrics


def qm_site_metadata(mdtop, spec: qp.QMRegionSpec, fp: qp.FramePartition,
                     resnum_offset: int) -> list[dict]:
    """Metadata for each QM coordinate, including synthetic link H sites.

    ``topology_atom_index`` is the robust zero-based atom identifier used by
    MDTraj/PartQMMM. ``topology_atom_id_1based`` is provided for convenient
    human-readable reporting. Link atoms have no topology atom id and are
    explicitly labeled as synthetic.
    """
    rows = []
    n_real = len(fp.qm_atom_indices)
    selected_water_resids = set(int(x) for x in fp.selected_water_resids)
    for qi, atom_index in enumerate(fp.qm_atom_indices):
        atom = mdtop.atom(atom_index)
        residue = atom.residue
        rows.append({
            "qm_site_index": qi,
            "is_link_atom": False,
            "link_index": None,
            "topology_atom_index": int(atom_index),
            "topology_atom_id_1based": int(atom_index) + 1,
            "element": fp.qm_elements[qi],
            "atom_label": atom_label(mdtop, atom_index, resnum_offset),
            "residue_index": int(residue.index),
            "resname": residue.name,
            "resseq": residue.resSeq,
            "pdb_resnum": protein_pdb_resnum(residue, resnum_offset),
            "atom_name": atom.name,
            "is_adaptive_qm_water": int(residue.index) in selected_water_resids,
        })
    for li, (cb, ca) in enumerate(spec.boundary_pairs):
        qi = n_real + li
        rows.append({
            "qm_site_index": qi,
            "is_link_atom": True,
            "link_index": int(li),
            "topology_atom_index": None,
            "topology_atom_id_1based": None,
            "element": "H",
            "atom_label": f"LINK_H{li}:{atom_label(mdtop, cb, resnum_offset)}-{atom_label(mdtop, ca, resnum_offset)}",
            "residue_index": None,
            "resname": "LINK",
            "resseq": None,
            "pdb_resnum": None,
            "atom_name": f"H_LINK_{li}",
            "is_adaptive_qm_water": False,
        })
    return rows


def site_specific_field_rows(per_qm: list[dict]) -> list[dict]:
    """Select chemically interpretable field sites for compact time-series output.

    The full ``qm_atom_fields.csv`` still contains every QM atom and link H.
    This reduced table focuses on: Zn; histidine ring nitrogens; glutamate
    carboxylate oxygens; and oxygen atoms of adaptive QM waters.  These are less
    likely than hydrogens to give misleadingly large local-field maxima and are
    directly relevant to the metal/solvent chemistry.
    """
    rows: list[dict] = []
    his_names = {"HIS", *[x.upper() for x in qp.HID_HIE_VARIANTS]}
    for row in per_qm:
        if row.get("is_link_atom"):
            continue
        resname = str(row.get("resname") or "").upper()
        atom_name = str(row.get("atom_name") or "").upper()
        element = str(row.get("element") or "").upper()
        site_class = None
        if element == "ZN":
            site_class = "ZN"
        elif resname in his_names and atom_name in {"ND1", "NE2"}:
            site_class = "HIS_N"
        elif resname in {"GLU", "GLH"} and atom_name in {"OE1", "OE2"}:
            site_class = "GLU_O"
        elif bool(row.get("is_adaptive_qm_water")) and element == "O":
            site_class = "QM_WATER_O"
        if site_class is None:
            continue
        out = dict(row)
        out["site_class"] = site_class
        out["site_label"] = row.get("atom_label", "")
        rows.append(out)
    return rows


def embedding_field_metrics(mdtop, spec: qp.QMRegionSpec, fp: qp.FramePartition,
                            resnum_offset: int,
                            shell_radii_A: tuple[float, ...] = (3.0, 4.0, 5.0),
                            charge_threshold_e: float = 1e-8,
                            chunk_size: int = 5000) -> tuple[dict, list[dict]]:
    """Evaluate the exact finite point-charge embedding field at every QM site.

    The coordinates in fp are already the imaged coordinates written to QM/MM
    files, so direct Euclidean distances are deliberate here (no second PBC
    transformation). RCD virtual sites are included when present.
    """
    qm = np.asarray(fp.qm_positions_A, dtype=float)
    mm = np.asarray(fp.mm_positions_A, dtype=float)
    q = np.asarray(fp.mm_charges, dtype=float)
    active = np.abs(q) > charge_threshold_e
    mm = mm[active]
    q = q[active]
    active_indices = np.flatnonzero(active)

    nq = len(qm)
    potential_raw = np.zeros(nq, dtype=float)
    field_raw = np.zeros((nq, 3), dtype=float)
    nearest_per_qm = np.full(nq, np.inf, dtype=float)
    nearest_charge_per_qm = np.full(nq, np.nan, dtype=float)
    nearest_site_per_qm = np.full(nq, -1, dtype=int)
    n_real_qm = len(fp.qm_atom_indices)
    shell_counts = {float(r): 0 for r in shell_radii_A}
    shell_counts_all = {float(r): 0 for r in shell_radii_A}
    topology_shell_counts = {float(r): 0 for r in shell_radii_A}
    nearest_global = (float("inf"), -1, -1)  # to real QM: distance, active mm idx, qm idx
    nearest_global_all = (float("inf"), -1, -1)
    nearest_topology = (float("inf"), -1, -1)

    for start in range(0, len(mm), max(1, int(chunk_size))):
        stop = min(len(mm), start + max(1, int(chunk_size)))
        pos = mm[start:stop]
        qc = q[start:stop]
        # Shape: (n_mm_chunk, n_qm, 3), vector from charge -> QM site.
        delta = qm[None, :, :] - pos[:, None, :]
        r2 = np.einsum("mqi,mqi->mq", delta, delta)
        if np.any(r2 < 1e-12):
            mi, qi = np.argwhere(r2 < 1e-12)[0]
            original_mm = int(active_indices[start + int(mi)])
            raise ValueError(
                f"nonzero MM embedding site {fp.mm_site_labels[original_mm]} overlaps "
                f"QM site {qi}; possible QM/MM double counting"
            )
        r = np.sqrt(r2)
        inv_r = 1.0 / r
        potential_raw += np.sum(qc[:, None] * inv_r, axis=0)
        field_raw += np.sum(
            qc[:, None, None] * delta * (inv_r ** 3)[:, :, None], axis=0
        )

        # Nearest nonzero embedding site to each QM site.
        local_min_idx = np.argmin(r, axis=0)
        local_min = r[local_min_idx, np.arange(nq)]
        improve = local_min < nearest_per_qm
        if np.any(improve):
            qids = np.flatnonzero(improve)
            nearest_per_qm[qids] = local_min[qids]
            nearest_charge_per_qm[qids] = qc[local_min_idx[qids]]
            nearest_site_per_qm[qids] = active_indices[start + local_min_idx[qids]]

        # Minimum distances of each embedding site to physical QM atoms and to
        # the complete QM coordinate list including artificial link H atoms.
        min_mm_all = np.min(r, axis=1)
        min_mm_real = np.min(r[:, :n_real_qm], axis=1) if n_real_qm else min_mm_all
        for radius in shell_counts:
            shell_counts[radius] += int(np.count_nonzero(min_mm_real <= radius))
            shell_counts_all[radius] += int(np.count_nonzero(min_mm_all <= radius))

        chunk_original = active_indices[start:stop]
        chunk_types = np.asarray([fp.mm_site_types[int(i)] for i in chunk_original], dtype=object)
        topo_mask = chunk_types == "topology"
        if np.any(topo_mask):
            topo_min = min_mm_real[topo_mask]
            for radius in topology_shell_counts:
                topology_shell_counts[radius] += int(np.count_nonzero(topo_min <= radius))
            topo_local_candidates = np.flatnonzero(topo_mask)
            tloc = int(topo_local_candidates[int(np.argmin(topo_min))])
            if min_mm_real[tloc] < nearest_topology[0]:
                qi = int(np.argmin(r[tloc, :n_real_qm])) if n_real_qm else int(np.argmin(r[tloc]))
                nearest_topology = (float(min_mm_real[tloc]), start + tloc, qi)

        mm_local = int(np.argmin(min_mm_real))
        if min_mm_real[mm_local] < nearest_global[0]:
            qi = int(np.argmin(r[mm_local, :n_real_qm])) if n_real_qm else int(np.argmin(r[mm_local]))
            nearest_global = (float(min_mm_real[mm_local]), start + mm_local, qi)
        mm_local_all = int(np.argmin(min_mm_all))
        if min_mm_all[mm_local_all] < nearest_global_all[0]:
            qi = int(np.argmin(r[mm_local_all]))
            nearest_global_all = (float(min_mm_all[mm_local_all]), start + mm_local_all, qi)

    potential_V = potential_raw * COULOMB_V_ANGSTROM_PER_E
    field_V_A = field_raw * COULOMB_V_ANGSTROM_PER_E
    field_mag = np.linalg.norm(field_V_A, axis=1)
    site_meta = qm_site_metadata(mdtop, spec, fp, resnum_offset)
    per_qm = []
    for qi, meta in enumerate(site_meta):
        mm_site_idx = int(nearest_site_per_qm[qi])
        row = dict(meta)
        row.update({
            "x_A": float(qm[qi, 0]),
            "y_A": float(qm[qi, 1]),
            "z_A": float(qm[qi, 2]),
            "potential_raw_e_per_A": float(potential_raw[qi]),
            "potential_V": float(potential_V[qi]),
            "field_x_raw_e_per_A2": float(field_raw[qi, 0]),
            "field_y_raw_e_per_A2": float(field_raw[qi, 1]),
            "field_z_raw_e_per_A2": float(field_raw[qi, 2]),
            "field_x_V_per_A": float(field_V_A[qi, 0]),
            "field_y_V_per_A": float(field_V_A[qi, 1]),
            "field_z_V_per_A": float(field_V_A[qi, 2]),
            "field_magnitude_V_per_A": float(field_mag[qi]),
            "nearest_mm_charge_distance_A": float(nearest_per_qm[qi]),
            "nearest_mm_charge_e": float(nearest_charge_per_qm[qi]),
            "nearest_mm_site_type": fp.mm_site_types[mm_site_idx] if mm_site_idx >= 0 else "",
            "nearest_mm_site_label": fp.mm_site_labels[mm_site_idx] if mm_site_idx >= 0 else "",
        })
        per_qm.append(row)

    real_field = field_mag[:len(fp.qm_atom_indices)]
    emax_idx = int(np.argmax(field_mag)) if len(field_mag) else -1
    emax_real_idx = int(np.argmax(real_field)) if len(real_field) else -1
    emax_meta = site_meta[emax_idx] if emax_idx >= 0 else {}
    emax_real_meta = site_meta[emax_real_idx] if emax_real_idx >= 0 else {}
    zn_field = math.nan
    zn_potential = math.nan
    zn_nearest_mm = math.nan
    if spec.metal_indices:
        zn_index = int(spec.metal_indices[0])
        for row in per_qm:
            if row.get("topology_atom_index") == zn_index:
                zn_field = float(row["field_magnitude_V_per_A"])
                zn_potential = float(row["potential_V"])
                zn_nearest_mm = float(row["nearest_mm_charge_distance_A"])
                break
    summary = {
        # Default nearest-MM diagnostic is to real QM atoms, not artificial link H.
        "nearest_mm_charge_to_qm_A": float(nearest_global[0]),
        "nearest_mm_charge_to_qm_including_links_A": float(nearest_global_all[0]),
        "nearest_topology_mm_charge_to_qm_A": float(nearest_topology[0]),
        "nearest_mm_charge_e": math.nan,
        "nearest_mm_site_type": "",
        "nearest_mm_site_label": "",
        "nearest_mm_qm_site_index": int(nearest_global[2]),
        "Emax_V_per_A": float(np.max(field_mag)) if len(field_mag) else math.nan,
        "Emean_V_per_A": float(np.mean(field_mag)) if len(field_mag) else math.nan,
        "Emax_real_qm_V_per_A": float(np.max(real_field)) if len(real_field) else math.nan,
        # Exact identity of the QM site carrying the frame-level maximum field.
        "Emax_qm_site_index": int(emax_idx),
        "Emax_is_link_atom": bool(emax_meta.get("is_link_atom", False)) if emax_idx >= 0 else False,
        "Emax_link_index": emax_meta.get("link_index"),
        "Emax_topology_atom_index": emax_meta.get("topology_atom_index"),
        "Emax_topology_atom_id_1based": emax_meta.get("topology_atom_id_1based"),
        "Emax_atom_label": emax_meta.get("atom_label", ""),
        "Emax_residue_index": emax_meta.get("residue_index"),
        "Emax_resname": emax_meta.get("resname", ""),
        "Emax_resseq": emax_meta.get("resseq"),
        "Emax_pdb_resnum": emax_meta.get("pdb_resnum"),
        "Emax_atom_name": emax_meta.get("atom_name", ""),
        "Emax_element": emax_meta.get("element", ""),
        # Same identity information with artificial link H atoms excluded.
        "Emax_real_qm_site_index": int(emax_real_idx),
        "Emax_real_topology_atom_index": emax_real_meta.get("topology_atom_index"),
        "Emax_real_topology_atom_id_1based": emax_real_meta.get("topology_atom_id_1based"),
        "Emax_real_atom_label": emax_real_meta.get("atom_label", ""),
        "Emax_real_residue_index": emax_real_meta.get("residue_index"),
        "Emax_real_resname": emax_real_meta.get("resname", ""),
        "Emax_real_resseq": emax_real_meta.get("resseq"),
        "Emax_real_pdb_resnum": emax_real_meta.get("pdb_resnum"),
        "Emax_real_atom_name": emax_real_meta.get("atom_name", ""),
        "Emax_real_element": emax_real_meta.get("element", ""),
        "potential_abs_max_V": float(np.max(np.abs(potential_V))) if len(potential_V) else math.nan,
        "E_Zn_V_per_A": zn_field,
        "potential_Zn_V": zn_potential,
        "nearest_mm_charge_to_Zn_A": zn_nearest_mm,
    }
    if nearest_global[1] >= 0:
        original_mm = int(active_indices[nearest_global[1]])
        summary["nearest_mm_charge_e"] = float(fp.mm_charges[original_mm])
        summary["nearest_mm_site_type"] = fp.mm_site_types[original_mm]
        summary["nearest_mm_site_label"] = fp.mm_site_labels[original_mm]
    for radius, count in shell_counts.items():
        summary[f"n_mm_charges_within_{radius:g}A"] = int(count)
        summary[f"n_mm_charges_within_{radius:g}A_including_links"] = int(shell_counts_all[radius])
        summary[f"n_topology_mm_charges_within_{radius:g}A"] = int(topology_shell_counts[radius])
    return summary, per_qm


def water_contact_category_counts(contacts: list[dict]) -> dict:
    by_group: dict[str, set[int]] = {}
    for c in contacts:
        by_group.setdefault(c["partner_group"], set()).add(c["water_residue_index"])
    out = {
        "n_azm_hbonded_waters": len(by_group.get("AZM", set())),
        "n_thr199_hbonded_waters": len(by_group.get("THR199", set())),
        "n_his_hbonded_waters": len(set().union(*[
            s for g, s in by_group.items() if g.startswith("HIS")
        ])) if any(g.startswith("HIS") for g in by_group) else 0,
    }
    return out
